-- Additive: preserves all existing template values and audit events.
ALTER TABLE outbound_email_events
 MODIFY COLUMN email_template ENUM('APPLICATION_RECEIVED','PAYMENT_SUCCESS','PAYMENT_FAILED','DOCUMENTS_REQUIRED','SUBMITTED','STATUS_CHANGED','VISA_ISSUED','RESUME_LINK','RECOVERY_OTP','SECURITY_DEPOSIT_REQUEST','REFUND_COMPLETED','DOCUMENTS_COMPLETE','PRODUCT_SUBSTITUTED','REJECTED','RESUME_REMINDER','REVIEW_REQUEST','APPROVAL_PENDING','GUARANTEE_BREACHED','CONNECTION_BROKEN','SUPPLIER_OVERRIDE','LICENCE_EXPIRY') NOT NULL;
