const creatives = [
  {id:'01',audience:'GCC Residents',format:'1:1 Static',title:'UAE Visa Support for GCC Residents',a:'GCC Resident? Plan Your UAE Visit',b:'Your UAE Visa Application, Online',cta:'Apply Online',score:95,image:'../generated/images/creative-01-gcc-static.png'},
  {id:'02',audience:'GCC Residents',format:'9:16 Reel',title:'Dubai trip on your mind?',a:'Dubai trip on your mind?',b:'GCC resident planning the UAE?',cta:'Apply Online',score:95,image:'../generated/images/creative-02-gcc-vertical.png',vertical:true},
  {id:'03',audience:'India',format:'9:16 Reel',title:'Planning a trip to Dubai?',a:'Planning a trip to Dubai?',b:'From trip idea to online application',cta:'Start Application',score:94,image:'../generated/images/creative-03-india-vertical.png',vertical:true},
  {id:'04',audience:'Egypt',format:'9:16 Reel',title:'Planning your UAE visit?',a:'Planning your UAE visit?',b:'A clear online application path',cta:'Apply Online',score:94,image:'../generated/images/creative-04-egypt-vertical.png',vertical:true},
  {id:'05',audience:'General',format:'Carousel',title:'How TASHIRA works',a:'Your UAE application in 5 clear steps',b:'How TASHIRA works',cta:'Start Application',score:96,image:'../generated/images/creative-05-carousel.png'},
  {id:'06',audience:'General / Trust',format:'9:16 Reel',title:'Know every step before you start',a:'A clearer way to apply online',b:'Know every step before you start',cta:'View Visa Options',score:95,image:'../generated/images/creative-06-trust-vertical.png',vertical:true}
];
const decisions = JSON.parse(localStorage.getItem('tashira-creative-decisions') || '{}');
const gallery = document.querySelector('#gallery');
function save(id,value,note=''){decisions[id]={value,note,at:new Date().toISOString()};localStorage.setItem('tashira-creative-decisions',JSON.stringify(decisions));render()}
function render(){gallery.innerHTML=creatives.map(c=>{const d=decisions[c.id]||{};return `<article class="card"><div class="visual ${c.vertical?'vertical':''}"><img src="${c.image}" alt="Creative ${c.id} key visual"><div class="shade"></div><div class="overlay"><span class="number">CREATIVE ${c.id}</span><h3>${c.title}</h3><span class="cta">${c.cta}</span></div></div><div class="body"><div class="meta"><span class="pill">${c.audience}</span><span class="pill">${c.format}</span></div><div class="hooks"><b>Hook A</b> — ${c.a}<br><b>Hook B</b> — ${c.b}</div><div class="scores"><span>Concept review</span><span class="score">${c.score}/100</span></div><div class="actions">${['APPROVE','REVISE','REJECT'].map(x=>`<button class="${d.value===x?'active':''}" data-id="${c.id}" data-action="${x}">${x}</button>`).join('')}</div><textarea class="note ${d.value==='REVISE'?'show':''}" data-note="${c.id}" placeholder="Revision notes…">${d.note||''}</textarea></div></article>`}).join('');document.querySelectorAll('button[data-action]').forEach(b=>b.onclick=()=>save(b.dataset.id,b.dataset.action,decisions[b.dataset.id]?.note||''));document.querySelectorAll('[data-note]').forEach(n=>n.onchange=()=>save(n.dataset.note,'REVISE',n.value))}
render();
