import { authorize, type AuthorizationActor } from "../authorization/policy";
import { isOperationsFlagEnabled, type FeatureFlagContext, type FeatureFlagRecord } from "../feature-flags/feature-flags";
import type { AuthorityQueryRecord, CreateAuthorityQuery, GenerateTypingPack, OperationalResource, TransitionAuthorityQuery } from "./mysql-authority-output-repository";
import type { TypingPack } from "./typing-pack";

export type AuthorityOutputRepository={context(applicationReference:string):Promise<OperationalResource|null>;query(queryId:string):Promise<AuthorityQueryRecord|null>;list(applicationReference:string):Promise<readonly AuthorityQueryRecord[]>;createQuery(input:CreateAuthorityQuery):Promise<AuthorityQueryRecord>;transition(input:TransitionAuthorityQuery):Promise<AuthorityQueryRecord>;generatePack(input:GenerateTypingPack):Promise<TypingPack>};
type Context={actor:AuthorizationActor;flagContext:FeatureFlagContext;flags:readonly FeatureFlagRecord[];repository:AuthorityOutputRepository};
function enabled(flag:"TYPING_PACK"|"AUTHORITY_QUERY",input:Context):void{if(!isOperationsFlagEnabled(flag,input.flagContext,input.flags))throw new Error(`${flag}_DISABLED`);}
function staffId(actor:AuthorizationActor):number{const match=/^staff:([1-9]\d*)$/.exec(actor.id);if(!match)throw new Error("AUTHORITY_OUTPUT_STAFF_REQUIRED");return Number(match[1]);}
function allowed(actor:AuthorizationActor,resource:OperationalResource):boolean{return authorize(actor,"authority.record_submission",{teamId:resource.teamId,departmentId:resource.departmentId}).allowed;}
async function context(input:Context,applicationReference:string):Promise<OperationalResource>{const resource=await input.repository.context(applicationReference);if(!resource||!allowed(input.actor,resource))throw new Error("AUTHORITY_OUTPUT_ACCESS_DENIED");return resource;}

export async function listAuthorityQueries(input:Context&{applicationReference:string}):Promise<readonly AuthorityQueryRecord[]>{enabled("AUTHORITY_QUERY",input);await context(input,input.applicationReference);return input.repository.list(input.applicationReference);}
export async function createAuthorityQuery(input:Context&{applicationReference:string;applicantId:number|null;authorityCode:string;queryType:string;commandId:string;reason:string;now:Date}):Promise<AuthorityQueryRecord>{enabled("AUTHORITY_QUERY",input);await context(input,input.applicationReference);return input.repository.createQuery({...input,actorStaffId:staffId(input.actor),occurredAt:input.now.toISOString()});}
export async function transitionAuthorityQuery(input:Context&{queryId:string;expectedVersion:number;state:TransitionAuthorityQuery["state"];commandId:string;reason:string;externalReference:string|null;now:Date}):Promise<AuthorityQueryRecord>{enabled("AUTHORITY_QUERY",input);const query=await input.repository.query(input.queryId);if(!query||!allowed(input.actor,query))throw new Error("AUTHORITY_OUTPUT_ACCESS_DENIED");return input.repository.transition({...input,actorStaffId:staffId(input.actor),occurredAt:input.now.toISOString()});}
export async function generateOperationalTypingPack(input:Context&{applicationReference:string;applicantId:number;templateCode:string;commandId:string;now:Date}):Promise<TypingPack>{enabled("TYPING_PACK",input);await context(input,input.applicationReference);return input.repository.generatePack({...input,actorStaffId:staffId(input.actor),occurredAt:input.now.toISOString()});}
