import { describe,expect,it } from "vitest";
import type { AuthorizationActor } from "../authorization/policy";
import type { FeatureFlagRecord } from "../feature-flags/feature-flags";
import { createAuthorityQuery,generateOperationalTypingPack,listAuthorityQueries,transitionAuthorityQuery,type AuthorityOutputRepository } from "./authority-output-service";

const resource={applicationId:1,applicationReference:"TSH-1",teamId:7,departmentId:2};
const event={eventId:"e-1",queryId:"q-1",applicationId:1,applicantId:3,state:"DRAFT" as const,occurredAt:"2026-08-26T10:00:00Z",actorType:"STAFF" as const,actorId:4,reason:"Synthetic query",externalReference:null};
const query={...resource,queryId:"q-1",applicantId:3,authorityCode:"SYNTHETIC_AUTHORITY",queryType:"STATUS_CHECK",state:"DRAFT" as const,version:1,history:[event]};
const actor=(teams=[7],permissions=["authority.record_submission"]):AuthorizationActor=>({id:"staff:4",permissions:new Set(permissions as ["authority.record_submission"]),scopes:["TEAM"],teamIds:new Set(teams),departmentIds:new Set()});
const flags:FeatureFlagRecord[]=[{flagKey:"AUTHORITY_QUERY",environment:"TEST",enabled:true,scopeType:"TEAM",scopeReference:"7"},{flagKey:"TYPING_PACK",environment:"TEST",enabled:true,scopeType:"TEAM",scopeReference:"7"}];
function repository():AuthorityOutputRepository&{writes:unknown[]}{const writes:unknown[]=[];return {writes,context:async()=>resource,query:async()=>query,list:async()=>[query],createQuery:async(input)=>{writes.push(input);return query;},transition:async(input)=>{writes.push(input);return {...query,state:input.state,version:2};},generatePack:async(input)=>{writes.push(input);return {packId:"p-1",applicationId:1,applicantId:3,templateId:"t-1",templateVersion:1,generatedAt:input.occurredAt,fields:[],evidenceReferences:["evaluation:e-1"],integritySha256:"a".repeat(64),state:"DRAFT_REQUIRES_HUMAN_REVIEW"};}};}
const base=(repo=repository())=>({actor:actor(),flagContext:{environment:"TEST" as const,staffId:4,teamIds:new Set([7])},flags,repository:repo});

describe("authority output service",()=>{
  it("fails closed behind independent flags",async()=>{const input=base();await expect(listAuthorityQueries({...input,flags:[],applicationReference:"TSH-1"})).rejects.toThrow("AUTHORITY_QUERY_DISABLED");await expect(generateOperationalTypingPack({...input,flags:[],applicationReference:"TSH-1",applicantId:3,templateCode:"SYNTHETIC",commandId:"1d7e57d0-ae21-4bcf-a8e0-6f16c927a003",now:new Date()})).rejects.toThrow("TYPING_PACK_DISABLED");});
  it("requires explicit permission and trusted team scope",async()=>{await expect(listAuthorityQueries({...base(),actor:actor([8]),applicationReference:"TSH-1"})).rejects.toThrow("AUTHORITY_OUTPUT_ACCESS_DENIED");await expect(listAuthorityQueries({...base(),actor:actor([7],[]),applicationReference:"TSH-1"})).rejects.toThrow("AUTHORITY_OUTPUT_ACCESS_DENIED");});
  it("derives staff identity and timestamps server-side",async()=>{const repo=repository(),input=base(repo),now=new Date("2026-08-26T12:00:00Z");await createAuthorityQuery({...input,applicationReference:"TSH-1",applicantId:3,authorityCode:"SYNTHETIC_AUTHORITY",queryType:"STATUS_CHECK",commandId:"f9fc3233-437b-4d56-97a6-ec5529fb26ff",reason:"Synthetic query",now});await transitionAuthorityQuery({...input,queryId:"q-1",expectedVersion:1,state:"SUBMITTED",commandId:"3e26b099-2ccd-4be1-9161-ddf5c729c11a",reason:"Controlled synthetic transition",externalReference:null,now});expect(repo.writes).toEqual([expect.objectContaining({actorStaffId:4,occurredAt:now.toISOString()}),expect.objectContaining({actorStaffId:4,occurredAt:now.toISOString()})]);});
  it("keeps Typing Pack response free of finance, payment and storage fields",async()=>{const result=await generateOperationalTypingPack({...base(),applicationReference:"TSH-1",applicantId:3,templateCode:"SYNTHETIC",commandId:"301b2259-7987-4527-8b7d-c2a0e5454086",now:new Date()});expect(JSON.stringify(result)).not.toMatch(/cost|margin|markup|profit|price|payment|stripe|storage/i);});
});
