import { randomUUID } from "node:crypto";
import type { Pool, PoolConnection, RowDataPacket } from "mysql2/promise";
import { prepareVisaDelivery, type VisaDeliveryPackage } from "./visa-delivery";

type SqlValue = string | number | Date | null;
export type VisaDeliveryResource = { applicationId: number; applicationReference: string; teamId: number; departmentId: number };
export type PrepareVisaDeliveryCommand = { applicationReference: string; applicantId: number; visaDocumentId: number; visaReference: string; validitySummary: string; customerInstructions: readonly string[]; commandId: string; actorReference: string; preparedAt: string };
export type VisaDeliveryView = Pick<VisaDeliveryPackage, "deliveryId"|"applicationId"|"applicantId"|"visaDocumentId"|"generatedAt"|"visaReference"|"validitySummary"|"customerInstructions"|"state"|"integritySha256">;
export type VisaDeliveryDocument = { delivery: VisaDeliveryView; storagePath: string };

function value(row: object, key: string): unknown { return Reflect.get(row, key); }
function text(row: object, key: string): string { const item=value(row,key); if(typeof item!=="string") throw new Error(`VISA_DELIVERY_ROW_INVALID:${key}`); return item; }
function integer(row: object, key: string): number { const item=Number(value(row,key)); if(!Number.isSafeInteger(item)||item<=0) throw new Error(`VISA_DELIVERY_ROW_INVALID:${key}`); return item; }
function dateTime(row: object,key:string):string { const item=value(row,key); if(item instanceof Date)return item.toISOString(); if(typeof item==="string"&&!Number.isNaN(Date.parse(item)))return new Date(item).toISOString(); throw new Error(`VISA_DELIVERY_ROW_INVALID:${key}`); }
function json<T>(row: object,key:string):T { const item=value(row,key); if(typeof item==="string")return JSON.parse(item) as T; if(Buffer.isBuffer(item))return JSON.parse(item.toString("utf8")) as T; return item as T; }
async function rows(connection:PoolConnection,sql:string,params:readonly SqlValue[]=[]):Promise<RowDataPacket[]> { const [result]=await connection.execute<RowDataPacket[]>(sql,[...params]); return result; }
const resourceSelect="SELECT a.id applicationId,a.reference_number applicationReference,c.team_id teamId,t.department_id departmentId FROM applications a JOIN operations_case_controls c ON c.application_id=a.id JOIN operations_teams t ON t.id=c.team_id";
const deliverySelect="SELECT d.id deliveryId,d.application_id applicationId,d.applicant_id applicantId,d.visa_document_id visaDocumentId,d.prepared_at generatedAt,d.visa_reference visaReference,d.validity_summary validitySummary,d.customer_instructions_json customerInstructions,d.state,d.integrity_sha256 integritySha256 FROM operations_visa_deliveries d JOIN applications a ON a.id=d.application_id";

export class MysqlVisaDeliveryRepository {
  private readonly pool: Pool;
  constructor(pool: Pool) { this.pool = pool; }
  async context(reference:string):Promise<VisaDeliveryResource|null>{const connection=await this.pool.getConnection();try{const found=await rows(connection,`${resourceSelect} WHERE a.reference_number=?`,[reference]);return found[0]?{applicationId:integer(found[0],"applicationId"),applicationReference:text(found[0],"applicationReference"),teamId:integer(found[0],"teamId"),departmentId:integer(found[0],"departmentId")}:null;}finally{connection.release();}}
  async listForCustomer(reference:string):Promise<readonly VisaDeliveryView[]>{const connection=await this.pool.getConnection();try{return (await rows(connection,`${deliverySelect} WHERE a.reference_number=? ORDER BY d.prepared_at,d.id`,[reference])).map((row)=>this.view(row));}finally{connection.release();}}
  async documentForCustomer(reference:string,deliveryId:string):Promise<VisaDeliveryDocument|null>{const connection=await this.pool.getConnection();try{const found=await rows(connection,`SELECT d.id deliveryId,d.application_id applicationId,d.applicant_id applicantId,d.visa_document_id visaDocumentId,d.prepared_at generatedAt,d.visa_reference visaReference,d.validity_summary validitySummary,d.customer_instructions_json customerInstructions,d.state,d.integrity_sha256 integritySha256,doc.storage_path storagePath FROM operations_visa_deliveries d JOIN applications a ON a.id=d.application_id JOIN documents doc ON doc.id=d.visa_document_id WHERE a.reference_number=? AND d.id=? AND doc.application_id=d.application_id AND doc.applicant_id=d.applicant_id AND doc.document_type='visa' AND doc.upload_status='uploaded'`,[reference,deliveryId]);return found[0]?{delivery:this.view(found[0]),storagePath:text(found[0],"storagePath")}:null;}finally{connection.release();}}
  async prepare(input:PrepareVisaDeliveryCommand):Promise<VisaDeliveryView>{const connection=await this.pool.getConnection();try{await connection.beginTransaction();const replay=await rows(connection,`${deliverySelect} WHERE a.reference_number=? AND d.idempotency_key=? FOR UPDATE`,[input.applicationReference,input.commandId]);if(replay[0]){const prior=this.view(replay[0]);if(prior.applicantId!==input.applicantId||prior.visaDocumentId!==input.visaDocumentId||prior.visaReference!==input.visaReference)throw new Error("VISA_DELIVERY_IDEMPOTENCY_CONFLICT");await connection.commit();return prior;}
    const evidence=await rows(connection,`SELECT a.id applicationId,a.reference_number applicationReference,ap.id applicantId,doc.id visaDocumentId,s.id scanId,s.evidence_sha256 scanEvidence FROM applications a JOIN applicants ap ON ap.application_id=a.id AND ap.id=? JOIN documents doc ON doc.application_id=a.id AND doc.applicant_id=ap.id AND doc.id=? AND doc.document_type='visa' AND doc.upload_status='uploaded' JOIN operations_document_security_scans s ON s.document_id=doc.id AND s.application_id=a.id AND s.applicant_id=ap.id WHERE a.reference_number=? ORDER BY s.scanned_at DESC,s.created_at DESC LIMIT 1 FOR UPDATE`,[input.applicantId,input.visaDocumentId,input.applicationReference]);if(!evidence[0])throw new Error("VISA_DELIVERY_OWNERSHIP_OR_SCAN_REQUIRED");const latest=evidence[0];const passed=await rows(connection,"SELECT result FROM operations_document_security_scans WHERE id=?",[text(latest,"scanId")]);if(!passed[0]||text(passed[0],"result")!=="PASSED")throw new Error("VISA_DELIVERY_SCAN_NOT_PASSED");
    const delivery=prepareVisaDelivery({deliveryId:randomUUID(),applicationId:integer(latest,"applicationId"),applicantId:integer(latest,"applicantId"),visaDocumentId:integer(latest,"visaDocumentId"),generatedAt:new Date(input.preparedAt).toISOString(),recipientReference:input.applicationReference,authorizedCustomer:true,virusScanPassed:true,documentOwnershipVerified:true,visaReference:input.visaReference,validitySummary:input.validitySummary,customerInstructions:input.customerInstructions,evidenceReferences:[`document:${input.visaDocumentId}`,`security-scan:${text(latest,"scanId")}`,`security-evidence:${text(latest,"scanEvidence")}`]});
    await connection.execute("INSERT INTO operations_visa_deliveries (id,application_id,applicant_id,visa_document_id,security_scan_id,recipient_reference,visa_reference,validity_summary,customer_instructions_json,evidence_references_json,state,integrity_sha256,prepared_by,idempotency_key,prepared_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[delivery.deliveryId,delivery.applicationId,delivery.applicantId,delivery.visaDocumentId,text(latest,"scanId"),delivery.recipientReference,delivery.visaReference,delivery.validitySummary,JSON.stringify(delivery.customerInstructions),JSON.stringify(delivery.evidenceReferences),delivery.state,delivery.integritySha256,input.actorReference,input.commandId,new Date(input.preparedAt)]);
    await connection.execute("INSERT INTO operations_audit_events (id,event_type,actor_type,actor_reference,resource_type,resource_reference,outcome,reason_code,metadata_json) VALUES (?,'VISA_DELIVERY_PREPARED','STAFF',?,'VISA_DELIVERY',?,'SUCCESS','SECURITY_SCAN_PASSED',?)",[randomUUID(),input.actorReference,delivery.deliveryId,JSON.stringify({applicationId:delivery.applicationId,applicantId:delivery.applicantId,documentId:delivery.visaDocumentId})]);await connection.commit();return this.view({...delivery,generatedAt:delivery.generatedAt});
  }catch(error){await connection.rollback();throw error;}finally{connection.release();}}
  private view(row:object):VisaDeliveryView{return {deliveryId:text(row,"deliveryId"),applicationId:integer(row,"applicationId"),applicantId:integer(row,"applicantId"),visaDocumentId:integer(row,"visaDocumentId"),generatedAt:dateTime(row,"generatedAt"),visaReference:text(row,"visaReference"),validitySummary:text(row,"validitySummary"),customerInstructions:Array.isArray(value(row,"customerInstructions"))?value(row,"customerInstructions") as string[]:json<string[]>(row,"customerInstructions"),state:text(row,"state") as "READY_FOR_SECURE_DELIVERY",integritySha256:text(row,"integritySha256")};}
}
