import { randomUUID } from "node:crypto";
import type { Pool, PoolConnection, ResultSetHeader, RowDataPacket } from "mysql2/promise";
import { AuthorityQueryTimeline, type AuthorityQueryEvent, type AuthorityQueryState } from "./authority-query";
import { generateTypingPack, humanVerificationFieldKeys, type TypingPack, type TypingPackField } from "./typing-pack";

type SqlValue = string | number | Date | null;
type TemplateField = { key: SupportedField; label: string; source: TypingPackField["source"] };
type SupportedField = "application.referenceNumber" | "applicant.fullName" | "applicant.passportNumber" | "applicant.nationality" | "applicant.passportExpiry" | "evaluation.routeCode" | "evaluation.eligibilityState";
export type OperationalResource = { applicationId: number; applicationReference: string; teamId: number; departmentId: number };
export type AuthorityQueryRecord = OperationalResource & { queryId: string; applicantId: number | null; authorityCode: string; queryType: string; state: AuthorityQueryState; version: number; history: readonly AuthorityQueryEvent[] };
export type CreateAuthorityQuery = { applicationReference: string; applicantId: number | null; authorityCode: string; queryType: string; commandId: string; actorStaffId: number; reason: string; occurredAt: string };
export type TransitionAuthorityQuery = { queryId: string; expectedVersion: number; state: Exclude<AuthorityQueryState,"DRAFT">; commandId: string; actorStaffId: number; reason: string; externalReference: string | null; occurredAt: string };
export type GenerateTypingPack = { applicationReference: string; applicantId: number; templateCode: string; commandId: string; actorStaffId: number; occurredAt: string };

function value(row:object,key:string):unknown{return Reflect.get(row,key);}
function text(row:object,key:string):string{const item=value(row,key);if(typeof item!=="string")throw new Error(`AUTHORITY_OUTPUT_ROW_INVALID:${key}`);return item;}
function nullableText(row:object,key:string):string|null{const item=value(row,key);if(item===null)return null;if(typeof item!=="string")throw new Error(`AUTHORITY_OUTPUT_ROW_INVALID:${key}`);return item;}
function integer(row:object,key:string):number{const item=Number(value(row,key));if(!Number.isSafeInteger(item))throw new Error(`AUTHORITY_OUTPUT_ROW_INVALID:${key}`);return item;}
function dateTime(row:object,key:string):string{const item=value(row,key);if(item instanceof Date)return item.toISOString();if(typeof item==="string"&&!Number.isNaN(Date.parse(item)))return new Date(item).toISOString();throw new Error(`AUTHORITY_OUTPUT_ROW_INVALID:${key}`);}
function json<T>(row:object,key:string):T{const item=value(row,key);if(typeof item==="string")return JSON.parse(item) as T;if(Buffer.isBuffer(item))return JSON.parse(item.toString("utf8")) as T;return item as T;}
async function rows(connection:PoolConnection,sql:string,parameters:readonly SqlValue[]=[]):Promise<RowDataPacket[]>{const [result]=await connection.execute<RowDataPacket[]>(sql,[...parameters]);return result;}

const resourceSelect=`SELECT a.id applicationId,a.reference_number applicationReference,c.team_id teamId,t.department_id departmentId FROM applications a JOIN operations_case_controls c ON c.application_id=a.id JOIN operations_teams t ON t.id=c.team_id`;
const querySelect=`SELECT q.id queryId,q.application_id applicationId,a.reference_number applicationReference,q.applicant_id applicantId,q.authority_code authorityCode,q.query_type queryType,q.current_state currentState,q.version,c.team_id teamId,t.department_id departmentId FROM operations_authority_queries q JOIN applications a ON a.id=q.application_id JOIN operations_case_controls c ON c.application_id=q.application_id JOIN operations_teams t ON t.id=c.team_id`;

export class MysqlAuthorityOutputRepository {
  private readonly pool:Pool;
  constructor(pool:Pool){this.pool=pool;}
  async context(applicationReference:string):Promise<OperationalResource|null>{const connection=await this.pool.getConnection();try{const found=await rows(connection,`${resourceSelect} WHERE a.reference_number=? LIMIT 1`,[applicationReference]);return found[0]?this.resource(found[0]):null;}finally{connection.release();}}
  async query(queryId:string):Promise<AuthorityQueryRecord|null>{const connection=await this.pool.getConnection();try{const found=await rows(connection,`${querySelect} WHERE q.id=?`,[queryId]);return found[0]?await this.queryRecord(connection,found[0]):null;}finally{connection.release();}}
  async list(applicationReference:string):Promise<readonly AuthorityQueryRecord[]>{const connection=await this.pool.getConnection();try{const found=await rows(connection,`${querySelect} WHERE a.reference_number=? ORDER BY q.created_at DESC,q.id`,[applicationReference]);return Promise.all(found.map((row)=>this.queryRecord(connection,row)));}finally{connection.release();}}
  async createQuery(input:CreateAuthorityQuery):Promise<AuthorityQueryRecord>{const connection=await this.pool.getConnection();try{await connection.beginTransaction();const resources=await rows(connection,`${resourceSelect} WHERE a.reference_number=? FOR UPDATE`,[input.applicationReference]);if(!resources[0])throw new Error("AUTHORITY_QUERY_APPLICATION_NOT_FOUND");const resource=this.resource(resources[0]);if(input.applicantId!==null){const owned=await rows(connection,"SELECT id FROM applicants WHERE id=? AND application_id=?",[input.applicantId,resource.applicationId]);if(!owned[0])throw new Error("AUTHORITY_QUERY_APPLICANT_OWNERSHIP_INVALID");}
    const replay=await rows(connection,"SELECT q.id queryId,q.applicant_id applicantId,q.authority_code authorityCode,q.query_type queryType,e.actor_reference actorReference,e.reason FROM operations_authority_query_events e JOIN operations_authority_queries q ON q.id=e.query_id WHERE q.application_id=? AND e.idempotency_key=?",[resource.applicationId,input.commandId]);if(replay[0]){const prior=replay[0];if((value(prior,"applicantId")===null?null:integer(prior,"applicantId"))!==input.applicantId||text(prior,"authorityCode")!==input.authorityCode||text(prior,"queryType")!==input.queryType||text(prior,"actorReference")!==`staff:${input.actorStaffId}`||text(prior,"reason")!==input.reason)throw new Error("AUTHORITY_QUERY_IDEMPOTENCY_CONFLICT");const result=await this.queryRecord(connection,(await rows(connection,`${querySelect} WHERE q.id=?`,[text(prior,"queryId")]))[0]);await connection.commit();return result;}
    const queryId=randomUUID(),eventId=randomUUID(),occurredAt=new Date(input.occurredAt);if(Number.isNaN(occurredAt.getTime()))throw new Error("AUTHORITY_QUERY_EVIDENCE_REQUIRED");
    const event:AuthorityQueryEvent={eventId,queryId,applicationId:resource.applicationId,applicantId:input.applicantId,state:"DRAFT",occurredAt:occurredAt.toISOString(),actorType:"STAFF",actorId:input.actorStaffId,reason:input.reason,externalReference:null};const timeline=new AuthorityQueryTimeline();timeline.append(event);
    await connection.execute("INSERT INTO operations_authority_queries (id,application_id,applicant_id,authority_code,query_type,current_state,version,created_by,created_at) VALUES (?,?,?,?,?,'DRAFT',1,?,?)",[queryId,resource.applicationId,input.applicantId,input.authorityCode,input.queryType,`staff:${input.actorStaffId}`,occurredAt]);
    await this.insertEvent(connection,event,0,1,input.commandId);await this.audit(connection,"AUTHORITY_QUERY_CREATED",queryId,input.actorStaffId,resource.applicationId,"DRAFT");await connection.commit();return {...resource,queryId,applicantId:input.applicantId,authorityCode:input.authorityCode,queryType:input.queryType,state:"DRAFT",version:1,history:[event]};
  }catch(error){await connection.rollback();throw error;}finally{connection.release();}}
  async transition(input:TransitionAuthorityQuery):Promise<AuthorityQueryRecord>{const connection=await this.pool.getConnection();try{await connection.beginTransaction();const found=await rows(connection,`${querySelect} WHERE q.id=? FOR UPDATE`,[input.queryId]);if(!found[0])throw new Error("AUTHORITY_QUERY_NOT_FOUND");const current=await this.queryRecord(connection,found[0]);const replay=await rows(connection,"SELECT state,version_before versionBefore,actor_reference actorReference,reason,external_reference externalReference FROM operations_authority_query_events WHERE query_id=? AND idempotency_key=?",[input.queryId,input.commandId]);if(replay[0]){const prior=replay[0];if(text(prior,"state")!==input.state||integer(prior,"versionBefore")!==input.expectedVersion||text(prior,"actorReference")!==`staff:${input.actorStaffId}`||text(prior,"reason")!==input.reason||nullableText(prior,"externalReference")!==input.externalReference)throw new Error("AUTHORITY_QUERY_IDEMPOTENCY_CONFLICT");await connection.commit();return current;}if(current.version!==input.expectedVersion)throw new Error("AUTHORITY_QUERY_VERSION_CONFLICT");
    const event:AuthorityQueryEvent={eventId:input.commandId,queryId:input.queryId,applicationId:current.applicationId,applicantId:current.applicantId,state:input.state,occurredAt:input.occurredAt,actorType:"STAFF",actorId:input.actorStaffId,reason:input.reason,externalReference:input.externalReference};const timeline=new AuthorityQueryTimeline();for(const prior of current.history)timeline.append(prior);timeline.append(event);const nextVersion=current.version+1;
    const [updated]=await connection.execute<ResultSetHeader>("UPDATE operations_authority_queries SET current_state=?,version=? WHERE id=? AND version=?",[input.state,nextVersion,input.queryId,current.version]);if(updated.affectedRows!==1)throw new Error("AUTHORITY_QUERY_VERSION_CONFLICT");await this.insertEvent(connection,event,current.version,nextVersion,input.commandId);await this.audit(connection,"AUTHORITY_QUERY_TRANSITION",input.queryId,input.actorStaffId,current.applicationId,input.state);await connection.commit();return {...current,state:input.state,version:nextVersion,history:[...current.history,event]};
  }catch(error){await connection.rollback();throw error;}finally{connection.release();}}
  async generatePack(input:GenerateTypingPack):Promise<TypingPack>{const connection=await this.pool.getConnection();try{await connection.beginTransaction();const existing=await rows(connection,"SELECT p.id packId,p.application_id applicationId,p.applicant_id applicantId,p.template_id templateId,p.template_snapshot_json templateSnapshot,p.fields_json fields,p.evidence_references_json evidenceReferences,p.state,p.integrity_sha256 integritySha256,p.generated_at generatedAt,p.generated_by generatedBy,a.reference_number applicationReference FROM operations_typing_packs p JOIN applications a ON a.id=p.application_id WHERE a.reference_number=? AND p.idempotency_key=? LIMIT 1",[input.applicationReference,input.commandId]);if(existing[0]){const prior=existing[0],snapshot=json<{templateCode:string;version:number}>(prior,"templateSnapshot");if(integer(prior,"applicantId")!==input.applicantId||snapshot.templateCode!==input.templateCode||text(prior,"generatedBy")!==`staff:${input.actorStaffId}`)throw new Error("TYPING_PACK_IDEMPOTENCY_CONFLICT");const fields=json<TypingPackField[]>(prior,"fields");await connection.commit();return {packId:text(prior,"packId"),applicationId:integer(prior,"applicationId"),applicantId:integer(prior,"applicantId"),templateId:text(prior,"templateId"),templateVersion:snapshot.version,generatedAt:dateTime(prior,"generatedAt"),fields,humanVerificationFieldKeys:humanVerificationFieldKeys(fields),evidenceReferences:json<string[]>(prior,"evidenceReferences"),state:text(prior,"state") as TypingPack["state"],integritySha256:text(prior,"integritySha256")};}
    const source=await rows(connection,`SELECT a.id applicationId,a.reference_number referenceNumber,ap.id applicantId,ap.full_name fullName,ap.passport_number passportNumber,ap.nationality,ap.passport_expiry passportExpiry,r.id evaluationId,r.route_code routeCode,r.final_eligibility_state eligibilityState FROM applications a JOIN applicants ap ON ap.application_id=a.id JOIN visa_rule_evaluation_selections s ON s.application_id=a.id AND s.applicant_id=ap.id JOIN visa_rule_evaluation_runs r ON r.id=s.evaluation_id WHERE a.reference_number=? AND ap.id=? ORDER BY s.selected_at DESC,s.id DESC LIMIT 1 FOR UPDATE`,[input.applicationReference,input.applicantId]);if(!source[0])throw new Error("TYPING_PACK_CURRENT_EVALUATION_REQUIRED");const row=source[0];
    const templates=await rows(connection,"SELECT id templateId,template_code templateCode,version,field_definitions_json fields,source_reference sourceReference FROM operations_typing_pack_templates WHERE template_code=? AND lifecycle_state='APPROVED' AND effective_from<=? AND (effective_to IS NULL OR effective_to>?) ORDER BY version DESC",[input.templateCode,new Date(input.occurredAt),new Date(input.occurredAt)]);if(templates.length!==1)throw new Error(templates.length?"TYPING_PACK_TEMPLATE_CONFLICT":"TYPING_PACK_APPROVED_TEMPLATE_REQUIRED");const template=templates[0],definitions=json<TemplateField[]>(template,"fields");const fields=definitions.map((definition)=>this.resolveField(definition,row));const packId=randomUUID(),evaluationId=text(row,"evaluationId"),templateId=text(template,"templateId");
    const pack=generateTypingPack({packId,applicationId:integer(row,"applicationId"),applicantId:integer(row,"applicantId"),templateId,templateVersion:integer(template,"version"),generatedAt:new Date(input.occurredAt).toISOString(),fields,evidenceReferences:[`evaluation:${evaluationId}`,`template:${templateId}:v${integer(template,"version")}`]});
    await connection.execute("INSERT INTO operations_typing_packs (id,application_id,applicant_id,evaluation_id,template_id,template_snapshot_json,fields_json,evidence_references_json,state,integrity_sha256,generated_by,idempotency_key,generated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)",[pack.packId,pack.applicationId,pack.applicantId,evaluationId,templateId,JSON.stringify({templateCode:text(template,"templateCode"),version:integer(template,"version"),sourceReference:text(template,"sourceReference")}),JSON.stringify(pack.fields),JSON.stringify(pack.evidenceReferences),pack.state,pack.integritySha256,`staff:${input.actorStaffId}`,input.commandId,new Date(input.occurredAt)]);await this.audit(connection,"TYPING_PACK_GENERATED",packId,input.actorStaffId,pack.applicationId,"DRAFT_REQUIRES_HUMAN_REVIEW");await connection.commit();return pack;
  }catch(error){await connection.rollback();throw error;}finally{connection.release();}}
  private resource(row:object):OperationalResource{return {applicationId:integer(row,"applicationId"),applicationReference:text(row,"applicationReference"),teamId:integer(row,"teamId"),departmentId:integer(row,"departmentId")};}
  private async queryRecord(connection:PoolConnection,row:object):Promise<AuthorityQueryRecord>{const events=await rows(connection,"SELECT id eventId,state,occurred_at occurredAt,actor_type actorType,actor_reference actorReference,reason,external_reference externalReference FROM operations_authority_query_events WHERE query_id=? ORDER BY version_after",[text(row,"queryId")]);const applicationId=integer(row,"applicationId"),applicantId=value(row,"applicantId")===null?null:integer(row,"applicantId");return {...this.resource(row),queryId:text(row,"queryId"),applicantId,authorityCode:text(row,"authorityCode"),queryType:text(row,"queryType"),state:text(row,"currentState") as AuthorityQueryState,version:integer(row,"version"),history:events.map((event)=>({eventId:text(event,"eventId"),queryId:text(row,"queryId"),applicationId,applicantId,state:text(event,"state") as AuthorityQueryState,occurredAt:dateTime(event,"occurredAt"),actorType:text(event,"actorType") as "STAFF"|"SYSTEM",actorId:nullableText(event,"actorReference")?.startsWith("staff:")?Number(nullableText(event,"actorReference")?.slice(6)):null,reason:text(event,"reason"),externalReference:nullableText(event,"externalReference")}))};}
  private async insertEvent(connection:PoolConnection,event:AuthorityQueryEvent,before:number,after:number,idempotencyKey:string):Promise<void>{await connection.execute("INSERT INTO operations_authority_query_events (id,query_id,state,version_before,version_after,actor_type,actor_reference,reason,external_reference,idempotency_key,occurred_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)",[event.eventId,event.queryId,event.state,before,after,event.actorType,event.actorId===null?null:`staff:${event.actorId}`,event.reason,event.externalReference,idempotencyKey,new Date(event.occurredAt)]);}
  private async audit(connection:PoolConnection,eventType:string,resourceReference:string,staffId:number,applicationId:number,reasonCode:string):Promise<void>{await connection.execute("INSERT INTO operations_audit_events (id,event_type,actor_type,actor_reference,resource_type,resource_reference,outcome,reason_code,metadata_json) VALUES (? ,?,'STAFF',?,'AUTHORITY_OUTPUT',?,'SUCCESS',?,?)",[randomUUID(),eventType,`staff:${staffId}`,resourceReference,reasonCode,JSON.stringify({applicationId})]);}
  private resolveField(definition:TemplateField,row:object):TypingPackField{const allowed:ReadonlySet<string>=new Set(["application.referenceNumber","applicant.fullName","applicant.passportNumber","applicant.nationality","applicant.passportExpiry","evaluation.routeCode","evaluation.eligibilityState"]);if(!allowed.has(definition.key)||!definition.label.trim())throw new Error("TYPING_PACK_TEMPLATE_FIELD_UNSUPPORTED");const column:Record<SupportedField,string>={"application.referenceNumber":"referenceNumber","applicant.fullName":"fullName","applicant.passportNumber":"passportNumber","applicant.nationality":"nationality","applicant.passportExpiry":"passportExpiry","evaluation.routeCode":"routeCode","evaluation.eligibilityState":"eligibilityState"};const expectedSource:Record<SupportedField,TypingPackField["source"]>={"application.referenceNumber":"APPLICATION","applicant.fullName":"APPLICANT","applicant.passportNumber":"APPLICANT","applicant.nationality":"APPLICANT","applicant.passportExpiry":"APPLICANT","evaluation.routeCode":"EVALUATION","evaluation.eligibilityState":"EVALUATION"};if(definition.source!==expectedSource[definition.key])throw new Error("TYPING_PACK_TEMPLATE_SOURCE_MISMATCH");const raw=value(row,column[definition.key]);if(raw===null||raw===undefined||String(raw).trim()==="")throw new Error("TYPING_PACK_SOURCE_FIELD_MISSING");return {key:definition.key,label:definition.label,source:expectedSource[definition.key],value:raw instanceof Date?raw.toISOString().slice(0,10):String(raw)};}
}
