import { randomUUID } from "node:crypto";
import type { Pool,PoolConnection,ResultSetHeader,RowDataPacket } from "mysql2/promise";
import type { RegulatoryChangeState,RegulatoryImpactArea } from "./regulatory-change-center";

type SqlValue=string|number|Date|null;
export type RegulatoryChangeRecord={changeId:string;sourceId:number;authority:string;sourceTitle:string;sourceUrl:string;previousSnapshotId:string;currentSnapshotId:string;previousFingerprint:string;currentFingerprint:string;proposedRuleVersion:number;currentRuleVersion:number|null;impactAreas:readonly RegulatoryImpactArea[];impactReasons:readonly string[];state:RegulatoryChangeState;version:number;changedAt:string;affectedApplications:readonly {applicationId:number;applicationReference:string;reason:string}[];history:readonly {eventId:string;decision:string;stateAfter:RegulatoryChangeState;versionBefore:number;versionAfter:number;actorReference:string;reason:string;occurredAt:string}[];activationAllowed:false;historicalMutationAllowed:false};
export type ProposeRegulatoryChangeCommand={sourceId:number;previousSnapshotId:string;currentSnapshotId:string;proposedRuleVersion:number;impactAreas:readonly RegulatoryImpactArea[];impactReasons:readonly string[];commandId:string;actorReference:string;occurredAt:string};
export type ReviewRegulatoryChangeCommand={changeId:string;decision:"START_REVIEW"|"APPROVE"|"REJECT"|"MARK_CONFLICT";expectedVersion:number;reason:string;commandId:string;actorReference:string;occurredAt:string};
function value(row:object,key:string):unknown{return Reflect.get(row,key);}function text(row:object,key:string):string{const item=value(row,key);if(typeof item!=="string")throw new Error(`REGULATORY_ROW_INVALID:${key}`);return item;}function integer(row:object,key:string):number{const item=Number(value(row,key));if(!Number.isSafeInteger(item))throw new Error(`REGULATORY_ROW_INVALID:${key}`);return item;}function nullableInteger(row:object,key:string):number|null{return value(row,key)===null?null:integer(row,key);}function dateTime(row:object,key:string):string{const item=value(row,key);if(item instanceof Date)return item.toISOString();if(typeof item==="string"&&!Number.isNaN(Date.parse(item)))return new Date(item).toISOString();throw new Error(`REGULATORY_ROW_INVALID:${key}`);}function json<T>(row:object,key:string):T{const item=value(row,key);if(typeof item==="string")return JSON.parse(item) as T;if(Buffer.isBuffer(item))return JSON.parse(item.toString("utf8")) as T;return item as T;}async function rows(connection:PoolConnection,sql:string,params:readonly SqlValue[]=[]):Promise<RowDataPacket[]>{const [result]=await connection.execute<RowDataPacket[]>(sql,[...params]);return result;}
const select=`SELECT c.id changeId,c.source_id sourceId,s.authority,s.title sourceTitle,s.source_url sourceUrl,c.previous_snapshot_id previousSnapshotId,c.current_snapshot_id currentSnapshotId,c.previous_fingerprint previousFingerprint,c.current_fingerprint currentFingerprint,c.proposed_rule_version proposedRuleVersion,c.current_rule_version currentRuleVersion,c.impact_areas_json impactAreas,c.impact_reasons_json impactReasons,c.current_state currentState,c.version,c.changed_at changedAt FROM operations_regulatory_changes c JOIN visa_rule_sources s ON s.id=c.source_id`;
const transitions:Readonly<Record<ReviewRegulatoryChangeCommand["decision"],readonly RegulatoryChangeState[]>>={START_REVIEW:["NEW"],APPROVE:["UNDER_REVIEW"],REJECT:["UNDER_REVIEW"],MARK_CONFLICT:["NEW","UNDER_REVIEW"]};
const target:Readonly<Record<ReviewRegulatoryChangeCommand["decision"],RegulatoryChangeState>>={START_REVIEW:"UNDER_REVIEW",APPROVE:"APPROVED",REJECT:"REJECTED",MARK_CONFLICT:"CONFLICT"};

export class MysqlRegulatoryChangeRepository{
 private readonly pool:Pool;constructor(pool:Pool){this.pool=pool;}
 async list():Promise<readonly RegulatoryChangeRecord[]>{const connection=await this.pool.getConnection();try{return Promise.all((await rows(connection,`${select} ORDER BY c.changed_at DESC,c.id`)).map(row=>this.record(connection,row)));}finally{connection.release();}}
 async get(changeId:string):Promise<RegulatoryChangeRecord|null>{const connection=await this.pool.getConnection();try{const found=await rows(connection,`${select} WHERE c.id=?`,[changeId]);return found[0]?this.record(connection,found[0]):null;}finally{connection.release();}}
 async propose(input:ProposeRegulatoryChangeCommand):Promise<RegulatoryChangeRecord>{const connection=await this.pool.getConnection();try{await connection.beginTransaction();const evidence=await rows(connection,`SELECT s.id sourceId,s.authority,s.title sourceTitle,s.source_url sourceUrl,s.classification,s.is_active sourceState,p.id previousSnapshotId,p.fingerprint_sha256 previousFingerprint,p.retrieved_at previousRetrievedAt,p.retrieval_status previousStatus,n.id currentSnapshotId,n.fingerprint_sha256 currentFingerprint,n.retrieved_at currentRetrievedAt,n.retrieval_status currentStatus,(SELECT MAX(v.version) FROM visa_rule_versions v JOIN visa_rule_source_snapshots x ON x.id=v.source_snapshot_id WHERE x.source_id=s.id) currentRuleVersion FROM visa_rule_sources s JOIN visa_rule_source_snapshots p ON p.source_id=s.id AND p.id=? JOIN visa_rule_source_snapshots n ON n.source_id=s.id AND n.id=? WHERE s.id=? FOR UPDATE`,[input.previousSnapshotId,input.currentSnapshotId,input.sourceId]);if(!evidence[0])throw new Error("REGULATORY_SOURCE_EVIDENCE_MISSING");const source=evidence[0];if(text(source,"classification")!=="OFFICIAL"||text(source,"sourceState")!=="ACTIVE"||text(source,"previousStatus")!=="SUCCESS"||text(source,"currentStatus")!=="SUCCESS")throw new Error("REGULATORY_SOURCE_NOT_AUTHORITATIVE");if(dateTime(source,"currentRetrievedAt")<=dateTime(source,"previousRetrievedAt")||text(source,"currentFingerprint")===text(source,"previousFingerprint"))throw new Error("REGULATORY_SNAPSHOT_CHANGE_INVALID");const currentRuleVersion=nullableInteger(source,"currentRuleVersion");if(input.proposedRuleVersion<=(currentRuleVersion??0)||input.impactAreas.length===0||input.impactReasons.length===0)throw new Error("REGULATORY_IMPACT_EVIDENCE_REQUIRED");
  const existing=await rows(connection,`${select} WHERE c.source_id=? AND c.previous_snapshot_id=? AND c.current_snapshot_id=?`,[input.sourceId,input.previousSnapshotId,input.currentSnapshotId]);if(existing[0]){const replay=await rows(connection,"SELECT actor_reference actorReference,reason FROM operations_regulatory_change_events WHERE change_id=? AND idempotency_key=? AND decision='PROPOSE'",[text(existing[0],"changeId"),input.commandId]);if(!replay[0])throw new Error("REGULATORY_CHANGE_ALREADY_EXISTS");if(text(replay[0],"actorReference")!==input.actorReference||text(replay[0],"reason")!==input.impactReasons.join(" | "))throw new Error("REGULATORY_IDEMPOTENCY_CONFLICT");await connection.commit();return this.record(connection,existing[0]);}
  const affected=await rows(connection,`SELECT DISTINCT a.id applicationId,a.reference_number applicationReference FROM visa_rule_evaluation_selections sel JOIN visa_rule_evaluation_matches m ON m.evaluation_id=sel.evaluation_id JOIN visa_rule_versions v ON v.id=m.rule_version_id JOIN applications a ON a.id=sel.application_id WHERE v.source_snapshot_id=? AND a.status NOT IN ('completed','rejected','cancelled')`,[input.previousSnapshotId]);const changeId=randomUUID(),occurredAt=new Date(input.occurredAt);if(Number.isNaN(occurredAt.getTime()))throw new Error("REGULATORY_REVIEW_EVIDENCE_REQUIRED");const impactAreas=[...new Set(input.impactAreas)].sort(),impactReasons=[...new Set(input.impactReasons)].sort();
  await connection.execute("INSERT INTO operations_regulatory_changes (id,source_id,previous_snapshot_id,current_snapshot_id,previous_fingerprint,current_fingerprint,proposed_rule_version,current_rule_version,impact_areas_json,impact_reasons_json,current_state,version,created_by,changed_at) VALUES (?,?,?,?,?,?,?,?,?,?,'NEW',1,?,?)",[changeId,input.sourceId,input.previousSnapshotId,input.currentSnapshotId,text(source,"previousFingerprint"),text(source,"currentFingerprint"),input.proposedRuleVersion,currentRuleVersion,JSON.stringify(impactAreas),JSON.stringify(impactReasons),input.actorReference,occurredAt]);for(const app of affected)await connection.execute("INSERT INTO operations_regulatory_change_impacts (change_id,application_id,reason) VALUES (?,?,?)",[changeId,integer(app,"applicationId"),"Current selected evaluation references the previous official source snapshot"]);await this.event(connection,changeId,"PROPOSE","NEW",0,1,input.actorReference,impactReasons.join(" | "),input.commandId,occurredAt);await this.audit(connection,"REGULATORY_CHANGE_PROPOSED",changeId,input.actorReference,{sourceId:input.sourceId,affectedApplications:affected.length});await connection.commit();return (await this.getWithin(connection,changeId))!;
 }catch(error){await connection.rollback();throw error;}finally{connection.release();}}
 async review(input:ReviewRegulatoryChangeCommand):Promise<RegulatoryChangeRecord>{const connection=await this.pool.getConnection();try{await connection.beginTransaction();const found=await rows(connection,`${select} WHERE c.id=? FOR UPDATE`,[input.changeId]);if(!found[0])throw new Error("REGULATORY_CHANGE_NOT_FOUND");const current=await this.record(connection,found[0]);const replay=await rows(connection,"SELECT decision,version_before versionBefore,actor_reference actorReference,reason FROM operations_regulatory_change_events WHERE change_id=? AND idempotency_key=?",[input.changeId,input.commandId]);if(replay[0]){if(text(replay[0],"decision")!==input.decision||integer(replay[0],"versionBefore")!==input.expectedVersion||text(replay[0],"actorReference")!==input.actorReference||text(replay[0],"reason")!==input.reason)throw new Error("REGULATORY_IDEMPOTENCY_CONFLICT");await connection.commit();return current;}if(current.version!==input.expectedVersion)throw new Error("REGULATORY_VERSION_CONFLICT");if(!transitions[input.decision].includes(current.state))throw new Error("REGULATORY_REVIEW_TRANSITION_INVALID");const next=target[input.decision],nextVersion=current.version+1;const [updated]=await connection.execute<ResultSetHeader>("UPDATE operations_regulatory_changes SET current_state=?,version=? WHERE id=? AND version=?",[next,nextVersion,input.changeId,current.version]);if(updated.affectedRows!==1)throw new Error("REGULATORY_VERSION_CONFLICT");await this.event(connection,input.changeId,input.decision,next,current.version,nextVersion,input.actorReference,input.reason,input.commandId,new Date(input.occurredAt));await this.audit(connection,"REGULATORY_CHANGE_REVIEWED",input.changeId,input.actorReference,{decision:input.decision,state:next});await connection.commit();return (await this.getWithin(connection,input.changeId))!;}catch(error){await connection.rollback();throw error;}finally{connection.release();}}
 private async getWithin(connection:PoolConnection,id:string):Promise<RegulatoryChangeRecord|null>{const found=await rows(connection,`${select} WHERE c.id=?`,[id]);return found[0]?this.record(connection,found[0]):null;}
 private async record(connection:PoolConnection,row:object):Promise<RegulatoryChangeRecord>{const id=text(row,"changeId");const [impacts,events]=await Promise.all([rows(connection,"SELECT i.application_id applicationId,a.reference_number applicationReference,i.reason FROM operations_regulatory_change_impacts i JOIN applications a ON a.id=i.application_id WHERE i.change_id=? ORDER BY a.reference_number",[id]),rows(connection,"SELECT id eventId,decision,state_after stateAfter,version_before versionBefore,version_after versionAfter,actor_reference actorReference,reason,occurred_at occurredAt FROM operations_regulatory_change_events WHERE change_id=? ORDER BY version_after",[id])]);return {changeId:id,sourceId:integer(row,"sourceId"),authority:text(row,"authority"),sourceTitle:text(row,"sourceTitle"),sourceUrl:text(row,"sourceUrl"),previousSnapshotId:text(row,"previousSnapshotId"),currentSnapshotId:text(row,"currentSnapshotId"),previousFingerprint:text(row,"previousFingerprint"),currentFingerprint:text(row,"currentFingerprint"),proposedRuleVersion:integer(row,"proposedRuleVersion"),currentRuleVersion:nullableInteger(row,"currentRuleVersion"),impactAreas:json<RegulatoryImpactArea[]>(row,"impactAreas"),impactReasons:json<string[]>(row,"impactReasons"),state:text(row,"currentState") as RegulatoryChangeState,version:integer(row,"version"),changedAt:dateTime(row,"changedAt"),affectedApplications:impacts.map(x=>({applicationId:integer(x,"applicationId"),applicationReference:text(x,"applicationReference"),reason:text(x,"reason")})),history:events.map(x=>({eventId:text(x,"eventId"),decision:text(x,"decision"),stateAfter:text(x,"stateAfter") as RegulatoryChangeState,versionBefore:integer(x,"versionBefore"),versionAfter:integer(x,"versionAfter"),actorReference:text(x,"actorReference"),reason:text(x,"reason"),occurredAt:dateTime(x,"occurredAt")})),activationAllowed:false,historicalMutationAllowed:false};}
 private async event(connection:PoolConnection,changeId:string,decision:string,state:string,before:number,after:number,actor:string,reason:string,key:string,at:Date):Promise<void>{if(!reason.trim()||Number.isNaN(at.getTime()))throw new Error("REGULATORY_REVIEW_EVIDENCE_REQUIRED");await connection.execute("INSERT INTO operations_regulatory_change_events (id,change_id,decision,state_after,version_before,version_after,actor_reference,reason,idempotency_key,occurred_at) VALUES (?,?,?,?,?,?,?,?,?,?)",[randomUUID(),changeId,decision,state,before,after,actor,reason,key,at]);}
 private async audit(connection:PoolConnection,eventType:string,reference:string,actor:string,metadata:object):Promise<void>{await connection.execute("INSERT INTO operations_audit_events (id,event_type,actor_type,actor_reference,resource_type,resource_reference,outcome,reason_code,metadata_json) VALUES (?,?,?,?,'REGULATORY_CHANGE',?,'SUCCESS','HUMAN_REVIEW_REQUIRED',?)",[randomUUID(),eventType,actor==="admin"?"ADMIN":"STAFF",actor,reference,JSON.stringify(metadata)]);}
}
