import { randomUUID } from "node:crypto";
import { createPool,type Pool,type ResultSetHeader } from "mysql2/promise";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { MysqlSupplierSlaRepository } from "./mysql-supplier-sla-repository";

const databaseUrl=process.env.OPS_SUPPLIER_SLA_DATABASE_URL;const integration=databaseUrl?describe.sequential:describe.skip;
function id(result:object):number{const value=Reflect.get(result,"insertId");if(typeof value!=="number"||value<1)throw new Error("SYNTHETIC_ID_INVALID");return value;}
integration("MySQL supplier SLA repository",()=>{let pool:Pool;let repository:MysqlSupplierSlaRepository;let reference="";let applicationId=0;const suffix=`${process.pid}-${Date.now()}`;
  beforeAll(async()=>{pool=createPool({uri:databaseUrl??"",connectionLimit:3});repository=new MysqlSupplierSlaRepository(pool);const [department]=await pool.execute<ResultSetHeader>("INSERT INTO operations_departments (code,name) VALUES (?,?)",[`SLA-${suffix}`,"Synthetic SLA"]);const departmentId=id(department);const [team]=await pool.execute<ResultSetHeader>("INSERT INTO operations_teams (department_id,code,name) VALUES (?,?,?)",[departmentId,`SLA-${suffix}`,"Synthetic SLA Team"]);const teamId=id(team);const [supplier]=await pool.execute<ResultSetHeader>("INSERT INTO suppliers (name,is_active) VALUES (?,'active')",[`Synthetic SLA Supplier ${suffix}`]);const supplierId=id(supplier);reference=`TSH-SLA-${suffix}`;const [application]=await pool.execute<ResultSetHeader>(`INSERT INTO applications (reference_number,base_type,residence_type,visa_type,processing_type,contact_email,contact_phone,exchange_rate,total_amount_aed,total_amount_usd,supplier_id,supplier_cost_aed,status,payment_status,data_classification) VALUES (?,'single','non-gcc','30-days','regular',?,'+000',3.67,500,136,?,321,'under_review','paid','TEST')`,[reference,`${suffix}@example.invalid`,supplierId]);applicationId=id(application);const [applicant]=await pool.execute<ResultSetHeader>("INSERT INTO applicants (application_id,applicant_index,full_name,nationality) VALUES (?,0,'Synthetic Applicant','SYN')",[applicationId]);const applicantId=id(applicant);await pool.execute("INSERT INTO operations_case_controls (application_id,team_id) VALUES (?,?)",[applicationId,teamId]);const evaluationId=randomUUID();await pool.execute(`INSERT INTO visa_rule_evaluation_runs (id,application_id,applicant_id,route_code,engine_version,final_eligibility_state,decision_reason,manual_review_reason,reevaluation_reason,required_documents_json,conditional_documents_json,warnings_json,precedence_trace_json,supersedes_evaluation_id,evidence_sha256,evaluated_at) VALUES (?,?,?,'UAE_30','synthetic','ELIGIBLE','Synthetic',NULL,NULL,'[]','[]','[]','[]',NULL,?,UTC_TIMESTAMP())`,[evaluationId,applicationId,applicantId,"a".repeat(64)]);await pool.execute("INSERT INTO visa_rule_evaluation_selections (id,application_id,applicant_id,evaluation_id,selection_reason,selected_by,selected_at) VALUES (?,?,?,?,?,'synthetic',UTC_TIMESTAMP())",[randomUUID(),applicationId,applicantId,evaluationId,"Synthetic current selection"]);await pool.execute(`INSERT INTO operations_supplier_sla_policies (id,supplier_id,route_code,version,acknowledgement_minutes,completion_minutes,warning_minutes_before_completion,lifecycle_state,source_reference,effective_from,created_by) VALUES (?,?, 'UAE_30',1,60,240,30,'ACTIVE','synthetic-approved',UTC_TIMESTAMP()-INTERVAL 1 DAY,'synthetic')`,[randomUUID(),supplierId]);});
  afterAll(async()=>{await pool.end();});
  it("starts from trusted application/evaluation policy and preserves replay/concurrency/audit evidence",async()=>{const started=await repository.start({applicationReference:reference,commandId:`start-${suffix}`,actorStaffId:7001,reason:"Synthetic supplier handoff",occurredAt:"2026-08-26T10:00:00.000Z"});expect(started).toMatchObject({applicationId,supplierId:expect.any(Number),routeCode:"UAE_30",state:"WAITING_FOR_ACKNOWLEDGEMENT",version:1});expect(await repository.start({applicationReference:reference,commandId:`start-${suffix}`,actorStaffId:7001,reason:"Synthetic supplier handoff",occurredAt:"2026-08-26T10:01:00.000Z"})).toEqual(started);const acknowledged=await repository.apply(started.slaId,{commandId:`ack-${suffix}`,expectedVersion:1,action:"ACKNOWLEDGE",actorStaffId:7001,reason:"Supplier acknowledged",occurredAt:"2026-08-26T10:30:00.000Z"});expect(acknowledged.version).toBe(2);expect(await repository.apply(started.slaId,{commandId:`ack-${suffix}`,expectedVersion:1,action:"ACKNOWLEDGE",actorStaffId:7001,reason:"Supplier acknowledged",occurredAt:"2026-08-26T10:31:00.000Z"})).toEqual(acknowledged);await expect(repository.apply(started.slaId,{commandId:`stale-${suffix}`,expectedVersion:1,action:"COMPLETE",actorStaffId:7001,reason:"Stale",occurredAt:"2026-08-26T12:00:00.000Z"})).rejects.toThrow("SUPPLIER_SLA_VERSION_CONFLICT");const completed=await repository.apply(started.slaId,{commandId:`complete-${suffix}`,expectedVersion:2,action:"COMPLETE",actorStaffId:7001,reason:"Supplier completed",occurredAt:"2026-08-26T13:00:00.000Z"});expect(completed).toMatchObject({state:"COMPLETED",version:3});const [audit]=await pool.query("SELECT id FROM operations_audit_events WHERE resource_type='SUPPLIER_SLA' AND resource_reference=?",[started.slaId]);expect(audit).toHaveLength(3);const [cost]=await pool.query("SELECT supplier_cost_aed supplierCost FROM applications WHERE id=?",[applicationId]);expect(cost).toEqual([expect.objectContaining({supplierCost:"321.00"})]);});
  it("enforces immutable policy and append-only event evidence",async()=>{await expect(pool.execute("UPDATE operations_supplier_sla_policies SET source_reference='changed' WHERE source_reference='synthetic-approved'")).rejects.toMatchObject({sqlState:"45000"});await expect(pool.execute("DELETE FROM operations_supplier_sla_events WHERE reason='Supplier completed'")).rejects.toMatchObject({sqlState:"45000"});});
});
