import { authorize,type AuthorizationActor } from "../authorization/policy";
import { isOperationsFlagEnabled,type FeatureFlagContext,type FeatureFlagRecord } from "../feature-flags/feature-flags";
import type { MysqlVisaDeliveryRepository,PrepareVisaDeliveryCommand,VisaDeliveryResource,VisaDeliveryView } from "./mysql-visa-delivery-repository";

export type VisaDeliveryRepository=Pick<MysqlVisaDeliveryRepository,"context"|"listForCustomer"|"documentForCustomer"|"prepare">;
type Flags={flagContext:FeatureFlagContext;flags:readonly FeatureFlagRecord[]};
function enabled(input:Flags):void{if(!isOperationsFlagEnabled("VISA_DELIVERY",input.flagContext,input.flags))throw new Error("VISA_DELIVERY_DISABLED");}
function allowed(actor:AuthorizationActor,resource:VisaDeliveryResource):boolean{return authorize(actor,"document.review",{teamId:resource.teamId,departmentId:resource.departmentId}).allowed;}
export async function prepareSecureVisaDelivery(input:Flags&{actor:AuthorizationActor;repository:VisaDeliveryRepository;applicationReference:string;applicantId:number;visaDocumentId:number;visaReference:string;validitySummary:string;customerInstructions:readonly string[];commandId:string;now:Date}):Promise<VisaDeliveryView>{enabled(input);const resource=await input.repository.context(input.applicationReference);if(!resource||!allowed(input.actor,resource))throw new Error("VISA_DELIVERY_ACCESS_DENIED");return input.repository.prepare({...input,actorReference:input.actor.id,preparedAt:input.now.toISOString()} satisfies PrepareVisaDeliveryCommand);}
export async function listCustomerVisaDeliveries(input:Flags&{repository:VisaDeliveryRepository;applicationReference:string;customerAuthorized:boolean}):Promise<readonly VisaDeliveryView[]>{enabled(input);if(!input.customerAuthorized)throw new Error("VISA_DELIVERY_CUSTOMER_AUTHORIZATION_REQUIRED");return input.repository.listForCustomer(input.applicationReference);}
export async function getCustomerVisaDeliveryDocument(input:Flags&{repository:VisaDeliveryRepository;applicationReference:string;deliveryId:string;customerAuthorized:boolean}){enabled(input);if(!input.customerAuthorized)throw new Error("VISA_DELIVERY_CUSTOMER_AUTHORIZATION_REQUIRED");const document=await input.repository.documentForCustomer(input.applicationReference,input.deliveryId);if(!document)throw new Error("VISA_DELIVERY_NOT_FOUND");return document;}
