import { describe,expect,it,vi } from "vitest";
import type { AuthorizationActor } from "../authorization/policy";
import type { FeatureFlagRecord } from "../feature-flags/feature-flags";
import { listCustomerVisaDeliveries,prepareSecureVisaDelivery,type VisaDeliveryRepository } from "./visa-delivery-service";

const flags:readonly FeatureFlagRecord[]=[{flagKey:"VISA_DELIVERY",environment:"TEST",enabled:true,scopeType:"APPLICATION",scopeReference:"TSH-1"}];
const view={deliveryId:"delivery-1",applicationId:1,applicantId:2,visaDocumentId:3,generatedAt:"2026-08-26T12:00:00.000Z",visaReference:"VISA-1",validitySummary:"Valid as printed",customerInstructions:["Check details"],state:"READY_FOR_SECURE_DELIVERY" as const,integritySha256:"a".repeat(64)};
function actor(team=7):AuthorizationActor{return {id:"staff:4",permissions:new Set(["document.review"]),scopes:["TEAM"],teamIds:new Set([team]),departmentIds:new Set()};}
function repository(applicationStatus:"visa_received"|"completed"|"under_review"="visa_received",paymentStatus="paid"):VisaDeliveryRepository{return {context:vi.fn(async()=>({applicationId:1,applicationReference:"TSH-1",teamId:7,departmentId:2,applicationStatus,paymentStatus})),listForCustomer:vi.fn(async()=>[view]),documentForCustomer:vi.fn(async()=>({delivery:view,storagePath:"applications/1/applicants/2/visa/file.pdf"})),prepare:vi.fn(async()=>view)};}
const base={flagContext:{environment:"TEST" as const,applicationReference:"TSH-1"},flags,applicationReference:"TSH-1",repository:repository()};
describe("visa delivery service",()=>{
  it("prepares through trusted scope and derives the actor/time server-side",async()=>{const repo=repository();await expect(prepareSecureVisaDelivery({...base,repository:repo,actor:actor(),applicantId:2,visaDocumentId:3,visaReference:"VISA-1",validitySummary:"Valid as printed",customerInstructions:["Check details"],commandId:"00000000-0000-4000-8000-000000000001",now:new Date("2026-08-26T12:00:00Z")})).resolves.toEqual(view);expect(repo.prepare).toHaveBeenCalledWith(expect.objectContaining({actorReference:"staff:4",preparedAt:"2026-08-26T12:00:00.000Z"}));});
  it("denies wrong-team and closed-flag staff writes",async()=>{await expect(prepareSecureVisaDelivery({...base,actor:actor(9),applicantId:2,visaDocumentId:3,visaReference:"VISA-1",validitySummary:"Valid",customerInstructions:["Check"],commandId:"00000000-0000-4000-8000-000000000001",now:new Date()})).rejects.toThrow("VISA_DELIVERY_ACCESS_DENIED");await expect(prepareSecureVisaDelivery({...base,flags:[],actor:actor(),applicantId:2,visaDocumentId:3,visaReference:"VISA-1",validitySummary:"Valid",customerInstructions:["Check"],commandId:"00000000-0000-4000-8000-000000000001",now:new Date()})).rejects.toThrow("VISA_DELIVERY_DISABLED");});
  it("fails closed until a paid application reaches the visa-issued state",async()=>{for(const repo of [repository("under_review"),repository("visa_received","pending")])await expect(prepareSecureVisaDelivery({...base,repository:repo,actor:actor(),applicantId:2,visaDocumentId:3,visaReference:"VISA-1",validitySummary:"Valid",customerInstructions:["Check"],commandId:"00000000-0000-4000-8000-000000000001",now:new Date()})).rejects.toThrow("VISA_DELIVERY_APPLICATION_STATE_REQUIRED");});
  it("permits an idempotent delivery replay after the issued case becomes completed",async()=>{await expect(prepareSecureVisaDelivery({...base,repository:repository("completed"),actor:actor(),applicantId:2,visaDocumentId:3,visaReference:"VISA-1",validitySummary:"Valid",customerInstructions:["Check"],commandId:"00000000-0000-4000-8000-000000000001",now:new Date()})).resolves.toEqual(view);});
  it("returns only owned customer-safe delivery metadata",async()=>{await expect(listCustomerVisaDeliveries({...base,customerAuthorized:true})).resolves.toEqual([view]);expect(JSON.stringify(view)).not.toMatch(/storage|bucket|path|provider/i);await expect(listCustomerVisaDeliveries({...base,customerAuthorized:false})).rejects.toThrow("VISA_DELIVERY_CUSTOMER_AUTHORIZATION_REQUIRED");});
});
