import { authorize,type AuthorizationActor } from "../authorization/policy";
import type { FeatureFlagContext,FeatureFlagRecord } from "../feature-flags/feature-flags";
import type { MysqlVisaDeliveryRepository,PrepareVisaDeliveryCommand,VisaDeliveryResource,VisaDeliveryView } from "./mysql-visa-delivery-repository";

export type VisaDeliveryRepository=Pick<MysqlVisaDeliveryRepository,"context"|"listForCustomer"|"documentForCustomer"|"prepare">;
type Flags={flagContext:FeatureFlagContext;flags:readonly FeatureFlagRecord[]};
function allowed(actor:AuthorizationActor,resource:VisaDeliveryResource):boolean{return authorize(actor,"document.review",{teamId:resource.teamId,departmentId:resource.departmentId,assignedActorId:resource.assignedActorId}).allowed;}
function canAttemptPreparation(resource:VisaDeliveryResource):boolean{return resource.paymentStatus==="paid"&&["visa_received","completed"].includes(resource.applicationStatus);}
export async function prepareSecureVisaDelivery(input:Flags&{actor:AuthorizationActor;repository:VisaDeliveryRepository;applicationReference:string;applicantId:number;visaDocumentId:number;visaReference:string;validitySummary:string;customerInstructions:readonly string[];commandId:string;now:Date}):Promise<VisaDeliveryView>{const resource=await input.repository.context(input.applicationReference);if(!resource||!allowed(input.actor,resource))throw new Error("VISA_DELIVERY_ACCESS_DENIED");if(!canAttemptPreparation(resource))throw new Error("VISA_DELIVERY_APPLICATION_STATE_REQUIRED");return input.repository.prepare({...input,actorReference:input.actor.id,preparedAt:input.now.toISOString()} satisfies PrepareVisaDeliveryCommand);}
export async function listCustomerVisaDeliveries(input:Flags&{repository:VisaDeliveryRepository;applicationReference:string;customerAuthorized:boolean}):Promise<readonly VisaDeliveryView[]>{if(!input.customerAuthorized)throw new Error("VISA_DELIVERY_CUSTOMER_AUTHORIZATION_REQUIRED");return input.repository.listForCustomer(input.applicationReference);}
export async function getCustomerVisaDeliveryDocument(input:Flags&{repository:VisaDeliveryRepository;applicationReference:string;deliveryId:string;customerAuthorized:boolean}){if(!input.customerAuthorized)throw new Error("VISA_DELIVERY_CUSTOMER_AUTHORIZATION_REQUIRED");const document=await input.repository.documentForCustomer(input.applicationReference,input.deliveryId);if(!document)throw new Error("VISA_DELIVERY_NOT_FOUND");return document;}
