import { describe,expect,it,vi } from "vitest";
import type { TrpcContext } from "./context";
import type { FeatureFlagRecord } from "./lib/feature-flags/feature-flags";
import type { AuthorizationActor } from "./lib/authorization/policy";
import type { VisaDeliveryRepository } from "./lib/operations/visa-delivery-service";
import { createOperationsVisaDeliveryRouter } from "./operations-visa-delivery-router";
const record:FeatureFlagRecord={flagKey:"VISA_DELIVERY",environment:"TEST",enabled:true,scopeType:"APPLICATION",scopeReference:"TSH-1"};
const view={deliveryId:"delivery-1",applicationId:1,applicantId:2,visaDocumentId:3,generatedAt:"2026-08-26T12:00:00.000Z",visaReference:"VISA-1",validitySummary:"Valid",customerInstructions:["Check"],state:"READY_FOR_SECURE_DELIVERY" as const,integritySha256:"a".repeat(64)};
const repository:VisaDeliveryRepository={context:vi.fn(async()=>({applicationId:1,applicationReference:"TSH-1",teamId:7,departmentId:2})),listForCustomer:vi.fn(async()=>[view]),documentForCustomer:vi.fn(async()=>({delivery:view,storagePath:"applications/1/applicants/2/visa/file.pdf"})),prepare:vi.fn(async()=>view)};
const trustedActor:AuthorizationActor={id:"staff:4",permissions:new Set(["document.review"]),scopes:["TEAM"],teamIds:new Set([7]),departmentIds:new Set()};
const router=createOperationsVisaDeliveryRouter({access:{actorForContext:vi.fn(async()=>trustedActor),flagContextForContext:vi.fn(async()=>({environment:"TEST" as const,staffId:4,teamIds:new Set([7])})),featureFlags:vi.fn(async()=>[record])},repository,now:()=>new Date("2026-08-26T12:00:00Z")});
function ctx(references:string[]=[],staffId?:number):TrpcContext{return {req:new Request("https://test.invalid"),resHeaders:new Headers(),isAdmin:false,staffId,customerApplicationReferences:new Set(references)};}
describe("operations visa delivery router",()=>{it("allows an owned customer and denies cross-application access",async()=>{await expect(router.createCaller(ctx(["TSH-1"])).customerList({applicationReference:"TSH-1"})).resolves.toEqual([view]);await expect(router.createCaller(ctx(["TSH-OTHER"])).customerList({applicationReference:"TSH-1"})).rejects.toMatchObject({code:"FORBIDDEN"});});it("issues only a short-lived signed URL after package ownership",async()=>{vi.stubEnv("STORAGE_URL_SECRET","synthetic-storage-secret-at-least-thirty-two-bytes");const result=await router.createCaller(ctx(["TSH-1"])).customerDownload({applicationReference:"TSH-1",deliveryId:"00000000-0000-4000-8000-000000000002"});expect(result.signedUrl).toMatch(/^\/storage\/applications\/1\/applicants\/2\/visa\/file.pdf\?expires=\d+&signature=/);expect(result).not.toHaveProperty("storagePath");vi.unstubAllEnvs();});it("keeps preparation staff-only",async()=>{await expect(router.createCaller(ctx([],4)).prepare({applicationReference:"TSH-1",applicantId:2,visaDocumentId:3,visaReference:"VISA-1",validitySummary:"Valid",customerInstructions:["Check"],commandId:"00000000-0000-4000-8000-000000000001"})).resolves.toEqual(view);});});
