import { TRPCError } from "@trpc/server";
import { z } from "zod";
import type { TrpcContext } from "./context";
import { MysqlOperationsAccessProvider,OperationsAccessError } from "./lib/operations/mysql-access-provider";
import { defaultOperationsPool,defaultOperationsSqlClient } from "./lib/operations/mysql-query-client";
import { MysqlAuthorityOutputRepository } from "./lib/operations/mysql-authority-output-repository";
import { createAuthorityQuery,generateOperationalTypingPack,listAuthorityQueries,transitionAuthorityQuery,type AuthorityOutputRepository } from "./lib/operations/authority-output-service";
import { createRouter,staffOrAdminQuery } from "./middleware";

type Access=Pick<MysqlOperationsAccessProvider,"actorForContext"|"flagContextForContext"|"featureFlags">;
type Dependencies={access:Access;repository:AuthorityOutputRepository;now():Date};
async function gate(deps:Dependencies,ctx:TrpcContext){if(!ctx.staffId)throw new TRPCError({code:"FORBIDDEN",message:"Authority output access denied"});const [actor,flagContext,flags]=await Promise.all([deps.access.actorForContext(ctx),deps.access.flagContextForContext(ctx),deps.access.featureFlags()]);return {actor,flagContext,flags,repository:deps.repository};}
function safe(error:unknown):never{if(error instanceof OperationsAccessError||error instanceof Error&&["TYPING_PACK_DISABLED","AUTHORITY_QUERY_DISABLED","AUTHORITY_OUTPUT_ACCESS_DENIED","AUTHORITY_OUTPUT_STAFF_REQUIRED"].includes(error.message))throw new TRPCError({code:"FORBIDDEN",message:"Authority output access denied"});if(error instanceof Error&&["AUTHORITY_QUERY_VERSION_CONFLICT","AUTHORITY_QUERY_IDEMPOTENCY_CONFLICT","TYPING_PACK_IDEMPOTENCY_CONFLICT"].includes(error.message))throw new TRPCError({code:"CONFLICT",message:"Authority output changed; refresh and retry"});if(error instanceof Error&&error.message==="AUTHORITY_QUERY_NOT_FOUND")throw new TRPCError({code:"NOT_FOUND",message:"Authority query not found"});throw new TRPCError({code:"BAD_REQUEST",message:"Authority output action could not be completed"});}
const reference=z.string().trim().min(3).max(50),commandId=z.string().uuid(),reason=z.string().trim().min(3).max(1000);
export function createOperationsAuthorityOutputRouter(deps:Dependencies){return createRouter({listQueries:staffOrAdminQuery.input(z.object({applicationReference:reference}).strict()).query(async({ctx,input})=>{try{return await listAuthorityQueries({...await gate(deps,ctx),...input});}catch(error){safe(error);}}),createQuery:staffOrAdminQuery.input(z.object({applicationReference:reference,applicantId:z.number().int().positive().nullable(),authorityCode:z.string().trim().min(2).max(100),queryType:z.string().trim().min(2).max(100),commandId,reason}).strict()).mutation(async({ctx,input})=>{try{return await createAuthorityQuery({...await gate(deps,ctx),...input,now:deps.now()});}catch(error){safe(error);}}),transitionQuery:staffOrAdminQuery.input(z.object({queryId:z.string().uuid(),expectedVersion:z.number().int().positive(),state:z.enum(["SUBMITTED","AWAITING_RESPONSE","RESPONSE_RECEIVED","CLOSED"]),commandId,reason,externalReference:z.string().trim().min(3).max(255).nullable()}).strict()).mutation(async({ctx,input})=>{try{return await transitionAuthorityQuery({...await gate(deps,ctx),...input,now:deps.now()});}catch(error){safe(error);}}),generateTypingPack:staffOrAdminQuery.input(z.object({applicationReference:reference,applicantId:z.number().int().positive(),templateCode:z.string().trim().min(2).max(100),commandId}).strict()).mutation(async({ctx,input})=>{try{return await generateOperationalTypingPack({...await gate(deps,ctx),...input,now:deps.now()});}catch(error){safe(error);}})});}
const access=new MysqlOperationsAccessProvider(defaultOperationsSqlClient());
export const operationsAuthorityOutputRouter=createOperationsAuthorityOutputRouter({access,repository:new MysqlAuthorityOutputRepository(defaultOperationsPool()),now:()=>new Date()});
